name: Bug report
description: Report a bug to help us improve
title: "[Bug] <title>"
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and expected behavior
      placeholder: "When I click X, Y fails..."
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      placeholder: "1) ... 2) ... 3) ..."
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: "Browser/OS/Node version"
