name: Feature request
description: Suggest an idea for this project
title: "[Feature] <title>"
labels: ["feature"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: "What problem does this solve?"
      description: "Describe the value and success criteria."
      value: ""
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      placeholder: "High-level tasks / acceptance criteria"
